#200: Fixed reuse database setup
exasol/script-languages-container-tool pull request #203
Opened 2023-06-22 08:57 UTC by tkilias

Fixes #200

2023-06-23 07:50 UTC, tkilias commented on exasol_script_languages_container_tool/lib/tasks/test/test_runner_db_test_task.py
> +        print("TestRunnerDBTestTask_kwargs", kwargs)
```suggestion
```

2023-06-23 07:50 UTC, tkilias commented on exasol_script_languages_container_tool/lib/tasks/test/test_runner_db_test_task.py
> +        print("reuse_databse_setup", reuse_databse_setup)
```suggestion
```

2023-06-23 10:32 UTC, ckunki requested changes

2023-06-23 10:32 UTC, ckunki commented on test/test_run_db_test_docker_db_reuse.py
> +        self.assertEqual(old_db_container_id, new_db_container_id)
```suggestion
from typing import Dict

    def get_docker_container_ids(self, *names) -> Dict[str, str]:
        result = {}
        with ContextDockerClient() as docker_client:
            for name in names:
                result[name] = docker_client.containers.get(name).id
        return result

    def test_reuse(self):
        def container_ids(command: List[str]) -> Dict[str, str]:
            self.test_environment.run_command(" ".join(command), track_task_dependencies=True)
            return get_docker_container_ids(
                self._test_container_name,
                self._db_container_name,
            )

        command = [f"{self.test_environment.executable}",
                   f"run-db-test",
                   f"{exaslct_utils.get_full_test_container_folder_parameter()}",
                   "--reuse-test-environment"]
        old_ids = container_ids(command)
        new_ids = container_ids(command)
        self.assertEqual(old_ids, new_ids)
```

2023-06-26 07:43 UTC, ckunki requested changes

2023-06-26 07:43 UTC, ckunki commented on exasol_script_languages_container_tool/lib/tasks/test/test_runner_db_test_task.py
> +        reuse = not (self.reuse_database_setup and self.test_environment_info.database_info.reused)
I still have the feeling that the name `reuse` is wrong as the Assigned boolean condition is wrapped in a `not()`.
Should the task `PopulateTestEngine` be created only if we can **not** reuse the database?
So the logic of the implementation is correct, but the naming is negated and hence contradicting the implementation.

Proposal: 
```python
reuse = self.reuse_database_setup and self.test_environment_info.database_info.reused
if not reuse:
```

2023-06-26 07:43 UTC, ckunki commented on test/test_run_db_test_docker_db_reuse.py
> +def get_docker_container_ids(self, *names) -> Dict[str, str]:
```suggestion
def get_docker_container_ids(*names) -> Dict[str, str]:
```

2023-06-26 07:59 UTC, tkilias commented on test/test_run_db_test_docker_db_reuse.py
> +def get_docker_container_ids(self, *names) -> Dict[str, str]:
good catch

2023-06-27 06:29 UTC, ckunki approved these changes

2023-06-27 07:06 UTC, merged